filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
      - drop_event:
          when:
            not:
              or:
                - equals:
                    container.name: "login_backend"
                - equals:
                    container.name: "campaign_service"
                - equals:
                    container.name: "login_backend_consumer"
                - equals:
                    container.name: "donation_service"
                - equals:
                    container.name: "payment_service"
                - equals:
                    container.name: "notification_service"
                - equals:
                    container.name: "login_kafka"
                - equals:
                    container.name: "login_db"
                - equals:
                    container.name: "campaign_redis"
                - equals:
                    container.name: "payment_db"

# Output to Elasticsearch with conditional indices
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "donation-logs-%{+yyyy.MM.dd}"
      when.contains:
        message: "donation"
    - index: "balance-logs-%{+yyyy.MM.dd}"
      when.contains:
        message: "balance"
    - index: "payment-logs-%{+yyyy.MM.dd}"
      when.contains:
        message: "payment"
    - index: "processing-logs-%{+yyyy.MM.dd}"
      when.contains:
        message: "processing"
    - index: "registration-logs-%{+yyyy.MM.dd}"
      when.contains:
        message: "register"
    - index: "campaign-logs-%{+yyyy.MM.dd}"
      when.contains:
        message: "campaign"
    - index: "filebeat-%{+yyyy.MM.dd}"

# Allow index name customization
setup.ilm.enabled: false
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

# Logging
logging.level: info
logging.to_stderr: true
